/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  json?: Json[];
  "install-packages"?: Modules;
  "remove-packages"?: Modules;
  "remove-files"?: string[];
}
export interface Json {
  src?: string;
  override?: {
    [k: string]: any;
  };
  remove?: {
    [k: string]: any;
  };
}
export interface Modules {
  dependencies?: string[];
  devDependencies?: string[];
}
